name: Fetcher

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  fetch:
    name: IETF Internet-Drafts fetching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Perform rsync from IETF
        run: |
          rsync -avcizxL rsync.ietf.org::bibxml-ids ./bibxml-ids

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install gem
        run: |
          gem install relaton-cli
      - name: Fetch documents
        run: |
          find ./data -name '*.yaml' | xargs rm -f
          relaton fetch-data ietf-internet-drafts
      - name: Push data
        run: |
          echo `date` > flag.txt
          git config user.name ietf-bib-bot
          git config user.email gh-bib-bot@llc.ietf.org
          git add flag.txt
          find ./data -name '*' | xargs git add
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
